const nodes={
  internet:{icon:'◎',title:'Internet',copy:'De externe verbinding met het homelab. Via een eigen netwerkopstelling wordt verkeer veilig en gecontroleerd naar de infrastructuur geleid.',tags:['WAN','NETWORK']},
  router:{icon:'⌁',title:'Home Router',copy:'Het centrale LAN-punt dat de thuisverbinding verdeelt. Tijdens de netwerkopzet vormde dit de eerste schakel richting de dedicated gateway.',tags:['LAN','ROUTING']},
  pi:{icon:'◈',title:'Raspberry Pi Gateway',copy:'Ingezet als router/gateway om het Ethernet-connectiviteitsprobleem van de HP ProDesk op te lossen. Een praktische oefening in routing, IP-adressering en NAT.',tags:['NAT','GATEWAY','TCP/IP']},
  hp:{icon:'▣',title:'HP ProDesk G4',copy:'De primaire bare-metal virtualisatiehost: Intel i5 (8e gen), 16 GB RAM en 512 GB SSD. Hier draait Proxmox VE als fundering voor het lab.',tags:['PROXMOX','16 GB RAM','512 GB SSD']},
  lenovo:{icon:'▤',title:'Lenovo ThinkStation',copy:'Een afzonderlijke compute-server met 40 GB RAM en 1 TB opslag, bedoeld voor zwaardere self-hosted workloads zoals lokale AI en Nextcloud.',tags:['40 GB RAM','LOCAL AI','NEXTCLOUD']},
  vm:{icon:'◇',title:'Debian Media VM',copy:'Een geïsoleerde Debian-omgeving voor Jellyfin, Sonarr, Radarr, Prowlarr en qBittorrent. Mullvad VPN draait hier bewust binnen de VM.',tags:['DEBIAN','JELLYFIN','MULLVAD']},
  cloud:{icon:'☁',title:'Self-hosted Services',copy:'Nextcloud en lokale AI-workloads draaien op de Lenovo, losgekoppeld van de primaire Proxmox-infrastructuur voor meer capaciteit en duidelijke scheiding.',tags:['NEXTCLOUD','LOCAL AI']}
};
const detail=document.querySelector('#node-detail');
document.querySelectorAll('.node').forEach(button=>button.addEventListener('click',()=>{const n=nodes[button.dataset.node];document.querySelectorAll('.node').forEach(x=>x.classList.remove('active'));button.classList.add('active');detail.innerHTML=`<p class="detail-kicker">${button.dataset.node.toUpperCase()} NODE</p><div class="detail-icon">${n.icon}</div><h3>${n.title}</h3><p class="detail-copy">${n.copy}</p><div class="detail-tags">${n.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="detail-footer"><span>STATUS</span><b><i></i> CONNECTED</b></div>`;}));
const cases={proxmox:{title:'Virtualisatie platform',copy:'De HP ProDesk fungeert als het hart van de infrastructuur. Proxmox VE is rechtstreeks op de hardware geïnstalleerd en maakt gecontroleerde service-isolatie mogelijk.',points:['Bare-metal Proxmox VE host','Debian VM voor de media stack','Experimenteren met storage en virtuele netwerken']},network:{title:'Van netwerkfout naar gateway',copy:'Toen de Ethernet-connectie op de HP niet correct opkwam, heb ik de volledige keten onderzocht: fysieke link, interface state, IP-configuratie, gateway en routing.',points:['Raspberry Pi als statische router/gateway','Praktische toepassing van NAT en default routes','Verbinding naar de Proxmox host hersteld']},security:{title:'Toegang met duidelijke grenzen',copy:'Remote beheer en privacygevoelig verkeer hebben elk een eigen plaats in de architectuur. Dat beperkt onnodige exposure en houdt verantwoordelijkheden duidelijk.',points:['Tailscale draait op de Proxmox host','Mullvad VPN is geïsoleerd in Debian','qBittorrent-verkeer wordt via de VPN geleid']}};
const modal=document.querySelector('#modal');document.querySelectorAll('.learn').forEach(b=>b.addEventListener('click',()=>{const c=cases[b.dataset.modal];modal.querySelector('h2').textContent=c.title;modal.querySelector('.modal-copy').textContent=c.copy;modal.querySelector('.modal-points').innerHTML=c.points.map(p=>`<p>${p}</p>`).join('');modal.showModal()}));document.querySelector('.close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
